find steam

diff --git a/star-server b/star-server
--- a/star-server
+++ b/star-server
@@ -40,6 +40,7 @@ BASH_QOL_MAIN="$INSTALL_PREFIX/lib/reiikz/bash-qol/common"
 BASH_QOL_FILES="$INSTALL_PREFIX/lib/reiikz/bash-qol/fileHandling"
 BASH_QOL_SCREEN="$INSTALL_PREFIX/lib/reiikz/bash-qol/screen"
 BASH_QOL_PROFILER="$INSTALL_PREFIX/lib/reiikz/bash-qol/profiler"
+BASH_QOL_STEAM="$INSTALL_PREFIX/lib/reiikz/bash-qol/steamcmd"
 YOUR_AWESM_COMMON_LIBRARY="$INSTALL_PREFIX/lib/reiikz/your-awesm/common"
 
 #load up main library
@@ -57,6 +58,10 @@ fi
 if ! source "$BASH_QOL_SCREEN"; then
 	echo -e "$FC_RED$FC_BOLD""Could not load Bash Quality of Life Screen library""$FC_RESET"
 	exit 0;
+fi
+
+if ! source "$BASH_QOL_STEAM"; then
+	echo -e "$FC_BOLD$FC_RED""Could not load  Bash Quality of Life steamcmd Library""$FC_RESET"
 fi
 
 # if ! source "$BASH_QOL_PROFILER"; then
