Split off work 1 Build script appears to work now, I still need to do a lot of work on splitting off the codebase but it seems functional atm. star-client doesn't do anything atm.

diff --git a/star-client b/star-client
--- a/star-client
+++ b/star-client
@@ -1,6 +1,68 @@
 #!/bin/bash
 
+#
+# MIT License
+#
+# Copyright (c) 2022 Reiikz
+#
+# Permission is hereby granted, free of charge, to any person obtaining a copy
+# of this software and associated documentation files (the "Software"), to deal
+# in the Software without restriction, including without limitation the rights
+# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
+# copies of the Software, and to permit persons to whom the Software is
+# furnished to do so, subject to the following conditions:
+#
+# The above copyright notice and this permission notice shall be included in all
+# copies or substantial portions of the Software.
+#
+# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
+# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
+# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
+# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
+# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
+# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
+# SOFTWARE.
+#
 
+VERSION="sid-(development version)"
+COPYRIGHT_YEAR="2022"
+SOURCE_URL="https://github.com/Reiikz/your-awesm"
+ERROR_REPORTING_TO="https://github.com/Reiikz/your-awesm/issues"
+DOCUMENTATION="https://github.com/Reiikz/your-awesm/wiki"
+CONFIGVER=2
+BUILT_FROM="(NON PACKAGED VERSION)"
 
+#STARBOUND APP ID, this is the Game's APP ID and it is used to download mods, do not change it
+APPID=211820
 
+# ~~~~~~~~~~~~~~~~~~~~~~~ SCRIPT STARTS HERE
 
+#load up main library
+if ! source "$MAIN_LIBRARY"; then
+	echo -e "$FC_RED$FC_BOLD""Could not load main library"
+	exit 0;
+fi
+
+MY_UID="your-awesm.$(basename ${BASH_SOURCE[0]}).$$"
+MYSELF="$(basename ${BASH_SOURCE[0]})"
+MY_SOURCE="${BASH_SOURCE[0]}"
+USER_HOME="$(getent passwd $(whoami) | cut -d':' -f6)"
+
+CONFIG_DIR="$USER_HOME/.config/RZ.star-server/$CONFIGVER"
+CACHE_DIR="$USER_HOME/.cache/RZ.star-server-cache"
+SERVER_WORKERS="$USER_HOME/.local/lib/RZ.star-server/1/server_workers"
+mkdir -p $CONFIG_DIR
+COLORFUL=1
+
+RECOMMEND_COOL_MODS="yes"
+declare -ga COOLMODS=( [0]="1958993491" )
+declare -gA COOLMODS_REASON=( [1958993491]="the maker of $MYSELF is an 8 headed dragon and this is an awesome dragon race, you should totally try it" )
+
+INSTALL_PREFIX="/usr/local"
+
+UNIT_FILE_TEMPLATE="$INSTALL_PREFIX/lib/reiikz/your-awesm/templates/template-unit-file.service"
+MAIN_LIBRARY="$INSTALL_PREFIX/lib/reiikz/your-awesm/common"
+
+if [ -f "$CONFIG_DIR/CLIENT_PRERUN" ]; then
+	source "$CONFIG_DIR/CLIENT_PRERUN"
+fi
diff --git a/star-server b/star-server
--- a/star-server
+++ b/star-server
@@ -48,27 +48,6 @@ BUILT_FROM="(NON PACKAGED VERSION)"
 APPID=211820
 
 # ~~~~~~~~~~~~~~~~~~~~~~~ SCRIPT STARTS HERE
-#FORMATTING CODES
-FC_RESET="\e[0m"
-FC_BOLD="\e[1m"
-
-#FORMATTING
-FC_DEFAULT_COLOR="\e[39m"
-FC_RED="\e[31m"
-FC_GREEN="\e[32m"
-FC_YELLOW="\e[33m"
-FC_BLUE="\e[34m"
-FC_MAGENTA="\e[35m"
-FC_CYAN="\e[36m"
-FC_LIGHT_GRAY="\e[37m"
-FC_DARK_GRAY="\e[90m"
-FC_LIGHT_RED="\e[91m"
-FC_LIGHT_GREEN="\e[92m"
-FC_LIGHT_YELLOW="\e[93m"
-FC_LIGHT_BLUE="\e[94m"
-FC_LIGHT_MAGENTA="\e[95m"
-FC_LIGHT_CYAN="\e[96m"
-FC_WHITE="\e[97m"
 
 MY_UID="your-awesm.$(basename ${BASH_SOURCE[0]}).$$"
 MYSELF="$(basename ${BASH_SOURCE[0]})"
@@ -89,10 +68,29 @@ INSTALL_PREFIX="/usr/local"
 
 UNIT_FILE_TEMPLATE="$INSTALL_PREFIX/lib/reiikz/your-awesm/templates/template-unit-file.service"
 MAIN_LIBRARY="$INSTALL_PREFIX/lib/reiikz/your-awesm/common"
+BASH_QOL_MAIN="$INSTALL_PREFIX/lib/reiikz/bash-qol/common"
+BASH_QOL_FILES="$INSTALL_PREFIX/lib/reiikz/bash-qol/fileHandling"
+BASH_QOL_SCREEN="$INSTALL_PREFIX/lib/reiikz/bash-qol/screen"
 
 #load up main library
+
+if ! source "$BASH_QOL_MAIN"; then
+	echo -e "Could not load Bash Quality of Life Main library"
+	exit 0;
+fi
+
+if ! source "$BASH_QOL_FILES"; then
+	echo -e "$FC_RED$FC_BOLD""Could not load Bash Quality of Life File handling library""$FC_RESET"
+	exit 0;
+fi
+
+if ! source "$BASH_QOL_SCREEN"; then
+	echo -e "$FC_RED$FC_BOLD""Could not load Bash Quality of Life Screen library""$FC_RESET"
+	exit 0;
+fi
+
 if ! source "$MAIN_LIBRARY"; then
-	echo -e "$FC_RED$FC_BOLD""Could not load main library"
+	echo -e "$FC_RED$FC_BOLD""Could not load main library""$FC_RESET"
 	exit 0;
 fi
 
@@ -101,96 +99,6 @@ if [ -f "$CONFIG_DIR/PRERUN" ]; then
 fi
 
 source $USER_HOME/.bashrc 2>/dev/null
-
-#DIR=$(dirname $0)
-#cd $DIR
-
-function toLower {
-	echo "$1" | tr '[:upper:]' '[:lower:]'
-}
-
-function isYes {
-	if [ "yes" == "$(toLower "$1")" ]; then
-		return 0
-	fi
-	return 1
-}
-
-function saveVar {
-	[ "$1" != "" ] && declare -p $1 > /dev/null 2> /dev/null || return 1
-    [ "$2" == "" ] && return 2
-	local dir="$2"
-    mkdir -p "$dir"
-    [ ! -w "$2" ] && return 3
-	if [ "$(toLower $3)" != "no" ] && [ "$3" != "0" ] && [ "$(toLower $3)" != "false" ]; then
-    	declare -p $1 | sed -E "s/^declare -/declare -g -/g" > "$dir/$1.bvar" 2> /dev/null
-	else
-		declare -p $1 > "$dir/$1.bvar" 2> /dev/null
-	fi
-    chmod 700 "$dir/$1.bvar"
-	# echo saving var $1 to $2
-	# declare -p $1
-	# cat $dir/$1.bvar
-}
-
-function loadVar {
-    unset "$1"
-    local dir="$2"
-    if ! source "$dir/$1.bvar" 2> /dev/null; then
-        return 1
-    else
-        declare -p $1 | sed -E "s/^declare -/declare -g -/g"
-        return 0
-    fi
-}
-
-function isArr {
-	if [ ! -z "$(grep -oE "^declare\s+-(a|A)" <<< "$(declare -p $1 2> /dev/null)")" ]; then
-		return 0
-	else
-		return 1
-	fi
-}
-
-function isAssoc {
-	if [ ! -z "$(grep -oE "^declare\s+-A" <<< "$(declare -p $1 2> /dev/null)")" ]; then
-		return 0
-	else
-		return 1
-	fi
-}
-
-function isInArray {
-    eval "$(echo "$1" | sed -E "s/^declare -/declare -g -/g" | sed -E "s/declare -g -a [A-Za-z0-9]+=/declare -g -a temporary=/g")"
-    for x in ${temporary[@]}; do
-        if [ "$2" == "$x" ]; then
-            unset temporary
-            return 0
-        fi
-    done
-    unset temporary
-    return 1
-}
-
-function timeYMD {
-	date "+%Y-%m-%d"
-}
-
-function timestamp {
-	date "+%s"
-}
-
-function unixToFormat {
-	date "$1" -d @$2
-}
-
-function unixToYMD {
-	unixToFormat "+%Y-%m-%d" "$1"
-}
-
-function logTimeFormat {
-	echo -n "[$(date "+%H:%m:%S")]:"
-}
 
 function makeSureLogIsNotTooOld {
 	local destination="$3"
@@ -258,20 +166,6 @@ function coecho {
 	fi
 }
 
-function linkify {
-    if [ "$COPY" == "1" ]; then
-        if ! cp -r "$1" "$2"; then
-			coecho "$FC_RED$FC_BOLD" "could not copy: \"$1\" to \"$2\""
-			return 1
-		fi
-    else
-        if ! ln -s "$(realpath --no-symlinks "$1")" "$(realpath --no-symlinks "$2")"; then
-			coecho "$FC_RED$FC_BOLD" "could not link: \"$1\" to \"$2\""
-			return 1
-		fi
-    fi
-}
-
 function checkPermission {
 	if [ -z "$SUDO_COMMAND" ] || [ "$(whoami)" == "root" ]; then
 		coecho "\e[1m\e[31m" "Not allowed"
@@ -284,82 +178,6 @@ function closeIfNotProfile {
 		coecho "$FC_LIGHT_GREEN$FC_BOLD" "Current profile is not set, please change your current profile with $FC_LIGHT_CYAN$MYSELF -s <profile name> $FC_LIGHT_GREEN""or $FC_LIGHT_CYAN$MYSELF -s <profile alias>"
 		exit 1
 	fi
-}
-
-function killScreen {
-	screen -X -S "$(isScreen "$1")" kill
-}
-
-function sendCommand {
-	[ $# -ne 2 ] && echo "bad usage of sendCommand" && exit 1
-	screen -S   $1 -p 0 -X stuff "$2^M"
-}
-
-function waitUntilRgex {
-	if [ $# -ne 3 ] && [ $# -ne 4 ]; then
-		echo "bad usage of waitUntil" && exit 1
-	fi
-	start=$(date "+%s")
-	screen -S   $1 -p 0 -X hardcopy "/tmp/$1.screen"
-	term=$(cat /tmp/$1.screen)
-	while [ -z "$(grep -oE "$2" <<< $term)" ]; do
-		screen -S   $1 -p 0 -X hardcopy "/tmp/$1.screen"
-		term=$(cat /tmp/$1.screen)
-		sleep 1
-		[ ! -z $4 ] && echo -n "$4"
-		if [ $(( $(date "+%s") - $start )) -ge $3 ]; then
-			FAIL=true
-			break
-		fi
-	done
-	#rm /tmp/$1.screen
-	[ ! -z $4 ] && echo ""
-}
-
-function isRegexThere {
-	[ -e "/tmp/$1.screen" ] && rm -rf "/tmp/$1.screen"
-	screen -S   $1 -p 0 -X hardcopy "/tmp/$1.screen"
-	term=$(cat /tmp/$1.screen)
-	if [ -z "$(grep -oE "$2" <<< $term)" ]; then
-		return 1
-	else
-		return 0
-	fi
-}
-
-function isLastLineRegex {
-	[ -e "/tmp/$1.screen" ] && rm -rf "/tmp/$1.screen"
-	screen -S   $1 -p 0 -X hardcopy "/tmp/$1.screen"
-	if [ -z "$(tail -n 1 /tmp/$1.screen | grep -oE "$2")" ]; then
-		return 1
-	else
-		return 0
-	fi
-}
-
-function waitUntil {
-	if [ $# -ne 3 ] && [ $# -ne 4 ]; then
-		echo "bad usage of waitUntil" && exit 1
-	fi
-	start=$(date "+%s")
-	screen -S   $1 -p 0 -X hardcopy "/tmp/$1.screen"
-	term=$(cat /tmp/$1.screen)
-	while [ -z "$(grep -o "$2" <<< $term)" ]; do
-		screen -S   $1 -p 0 -X hardcopy "/tmp/$1.screen"
-		term=$(cat /tmp/$1.screen)
-		sleep 1
-		[ ! -z $4 ] && echo -n "$4"
-		if [ $(( $(date "+%s") - $start )) -ge $3 ]; then
-			FAIL=true
-			break
-		fi
-	done
-	#rm /tmp/$1.screen
-	[ ! -z $4 ] && echo ""
-}
-
-function isScreen {
-	echo -n "$(screen -ls | grep -oE "[0-9]+\.$1\s{1}" | sed -e "s/\..*$//g")"
 }
 
 function printOptions {
@@ -387,124 +205,6 @@ function printOptions {
 
 function cleanup {
 	rm -rf /tmp/$MY_UID*
-}
-
-function findSteam {
-	if [ -d "$USER_HOME/.steam/steam/steamapps" ]; then
-		declare -g -- STEAM="$USER_HOME/.steam/steam/steamapps"
-		return 0
-	fi
-
-	if [ -d "$USER_HOME/.steam/steam/SteamApps" ]; then
-		declare -g -- STEAM="$USER_HOME/.steam/steam/SteamApps"
-		return 0
-	fi
-
-	if [ -d "$USER_HOME/.steam/debian-installation/steamapps" ]; then
-		declare -g -- STEAM="$USER_HOME/.steam/debian-installation/steamapps"
-		return 0
-	fi
-
-	if [ -d "$USER_HOME/Steam/steamapps" ]; then
-		declare -g -- STEAM="$USER_HOME/Steam/steamapps"
-		return 0
-	fi
-	
-	coecho "$FC_LIGHT_YELLOW$FC_BOLD" "Steam folder not found running 'steamcmd \"+quit\"'"
-	mkdir -p ${PROFILE[DUMP_FILES]}
-
-	mkdir -p ${PROFILE[DUMP_FILES]}
-	/usr/games/steamcmd "+quit" 2>&1 > ${PROFILE[DUMP_FILES]}/latestSteamCMDdump.stdout
-
-	if [ -d "$USER_HOME/Steam/steamapps" ]; then
-		declare -g -- STEAM="$USER_HOME/Steam/steamapps"
-		return 0
-	fi
-
-	if [ -d "$USER_HOME/.steam/steam/steamapps" ]; then
-		declare -g -- STEAM="$USER_HOME/.steam/steam/steamapps"
-		return 0
-	fi
-
-	if [ -d "$USER_HOME/.steam/steam/SteamApps" ]; then
-		declare -g -- STEAM="$USER_HOME/.steam/steam/SteamApps"
-		return 0
-	fi
-
-	if [ -d "$USER_HOME/.steam/debian-installation/steamapps" ]; then
-		declare -g -- STEAM="$USER_HOME/.steam/debian-installation/steamapps"
-		return 0
-	fi
-
-	coecho "$FC_LIGHT_RED$FC_BOLD" "OOPS Steam could not be found"
-	exit 1
-}
-
-function getModName {
-	local id="$1"
-	if [ -f "$CACHE_DIR/modnames/$id.name" ]; then
-		local c=0
-		while [ -z "$(cat $CACHE_DIR/modnames/$id.name)" ]; do
-			mkdir -p $CACHE_DIR/modnames
-			echo "$(wget "https://steamcommunity.com/sharedfiles/filedetails/?id=$id" -O - 2> /dev/null | grep -oP "(?<=<div class\=(\"|\')workshopItemTitle(\"|\')>)(.*)(?=<\/div>)")" > $CACHE_DIR/modnames/$id.name
-			c=$(($c+1))
-			if [ $c -gt 5 ]; then
-				break
-			fi
-		done
-		echo "$(cat $CACHE_DIR/modnames/$id.name)"
-	else
-		mkdir -p $CACHE_DIR/modnames
-		local name="$(wget "https://steamcommunity.com/sharedfiles/filedetails/?id=$id" -O - 2> /dev/null | grep -oP "(?<=<div class\=(\"|\')workshopItemTitle(\"|\')>)(.*)(?=<\/div>)")"
-		echo "$name" > $CACHE_DIR/modnames/$id.name
-		echo "$name"
-	fi
-
-}
-
-function parseModpack {
-	if [ -z "$(grep -oE "^(http|https)://steamcommunity.com/sharedfiles/filedetails/\?id=[0-9]+" <<< $1)" ]; then
-		coecho "$FC_LIGHT_RED$FC_BOLD" "$1: is not a valid workshop link"
-		exit 1
-	fi
-	rm -f /tmp/$MY_UID.workshop.html
-	wget $1 -O /tmp/$MY_UID.workshop.html 2> /dev/null
-	PARSED_MODPACK[RAW]="$(cat /tmp/$MY_UID.workshop.html)"
-	PARSED_MODPACK[NAME]="$(echo "${PARSED_MODPACK[RAW]}" | grep -oE "<div\s+class=\"workshopItemTitle\">.+</div>" | head -n 1 | sed -E "s/(<div\s+class=\"workshopItemTitle\">|<\/div>)//g")"
-	local items="$(echo "${PARSED_MODPACK[RAW]}" | tr -d \\n | grep -oE "<div\s+class=(\"|\')collectionItemDetails(\"|\')>\s*<a\s*href=(\"|\')http(s)*\:\/\/steamcommunity\.com\/sharedfiles\/filedetails\/\?id=[0-9]+(\"|\')\s*>")"
-	[ "$items" == "" ] && return 1
-	local c=0
-	while read -r line; do
-		local link="$(grep -oE "http(s)*\:\/\/steamcommunity\.com\/sharedfiles\/filedetails\/\?id=[0-9]+" <<< $line)"
-		[ "$link" == "" ] && continue
-		local id="$(grep -oE "id=[0-9]+" <<< $link | grep -oE "[0-9]+")"
-		PARSED_MODPACK["$id"~link]="$link"
-		PARSED_MODPACK[$c~id]="$id"
-		PARSED_MODPACK[$c~link]="$link"
-
-		if [ -f $CACHE_DIR/modnames/$id.name ]; then
-			PARSED_MODPACK[$c~name]="$(cat $CACHE_DIR/modnames/$id.name)"
-			PARSED_MODPACK[$id~name]="$(cat $CACHE_DIR/modnames/$id.name)"
-		else
-			mkdir -p $CACHE_DIR/modnames
-			local name="$(wget "$link" -O - 2> /dev/null | grep -oP "(?<=<div class\=(\"|\')workshopItemTitle(\"|\')>)(.*)(?=<\/div>)")"
-			echo "$name" > $CACHE_DIR/modnames/$id.name
-			PARSED_MODPACK[$c~name]="$name"
-			PARSED_MODPACK[$id~name]="$name"
-		fi
-		c=$(($c+1))
-		coecho "$FC_CYAN" "Found Content: ${PARSED_MODPACK[$id~name]} ($id)"
-
-	done <<< $items
-	if [ $c -eq 0 ]; then
-		PARSED_MODPACK[~modCount]="$c"
-		return 2
-	fi
-	PARSED_MODPACK[~lastItem]="$(($c-1))"
-	PARSED_MODPACK[~modCount]="$c"
-	coecho "$FC_LIGHT_GREEN$FC_BOLD" "Parsed modpack '${PARSED_MODPACK[NAME]}', $c workshop items found"
-	cleanup
-	return 0
 }
 
 function loadMods {
